### PR TITLE
Update to chef 16

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by TheREK3R** [comment]
[chef 16: osl-ceph](https://trello.com/c/speZdV9F/1982-chef-16-osl-ceph)

**Comment by TheREK3R** [comment]
oops there are a LOT of cookstyle errors, hold off on this one sorry

**Comment by TheREK3R** [comment]
nvm turns out these were from the cookbooks dir good to go

**Comment by ramereth** [comment]
@TheREK3R I'm having some trouble ChefSpec due to the fact the ceph-chef cookbook is still using chef-sugar. I think you should work on getting ceph-chef ready for Chef 16 first before this cookbook.

**Comment by TheREK3R** [comment]
Will do

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v3.4.0.  Have a nice day!

**Pull request merged**
